version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://postgres:SamiChehula@database-2.cpumios2mg8r.eu-north-1.rds.amazonaws.com/postgres?schema=public"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: .\frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SamiChehula
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
